Visit oromia feature
amanuelbelete95/capstone1-visit-oromia pull request #1
Opened 2023-02-08 19:04 UTC by amanuelbelete95

**List of Completed Activity**

- Designed a new capstone project
- Followed design guidelines
- Designed the two-page home page and about page
- Designed for Mobile: up to 768px wide.
- Designed for Desktop: 768px or wider
- The home page has a link in the menu to the about page.
- The logo in the header links to the home page.
- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
- The mobile menu has a close (X) button that closes the menu
- The section "Featured speakers" was created dynamically in JavaScript.

2023-02-08 19:10 UTC, huseyinbiyik commented
Hi @amanuelbelete95  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

You have submitted a project, that linter checks are not passing. Kindly fix the linter issues before submitting for review.
<img width="873" alt="Screenshot 2023-02-08 at 10 08 49 PM" src="https://user-images.githubusercontent.com/25887253/217628129-5c852135-317f-4f2a-88d6-35b5fad97c84.png">

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-09 13:06 UTC, roshan-bajgain requested changes
Hi @amanuelbelete95, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-02-09 13:06 UTC, roshan-bajgain commented on README.md
> +- **Website for visitors and tourist**
- [ ] As per the requirement you should create a video with a maximum length of 5 minutes which contains
`A description of the project.
A demo of the project features (different pages and different screen sizes).
You should also highlight some interesting piece of code or something you built that you are very proud of.`

2023-02-09 13:06 UTC, roshan-bajgain commented on README.md
- [ ] As per the requirement your acknowledgments should give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). Please include this

2023-02-09 13:06 UTC, roshan-bajgain commented on index.html
> +                <li class="red-border"><a href="">CC Campaign</a></li>
- [ ] As per the requirement you should stick to the design as much as possible. The black navbar with a list on the right is missing please implement that and make sure your design matches the original design.
- [ ] If you see the color of the list below that then you will find different colors please use the same color in the list and `CCampaign`
### Your design
![his](https://user-images.githubusercontent.com/81727988/217805125-3f0003bc-9055-43c6-910e-5b84cc365c87.png)

### Original design
![original](https://user-images.githubusercontent.com/81727988/217805148-da50e641-e279-40f3-810f-bd2346b1eb00.png)

2023-02-09 13:06 UTC, roshan-bajgain commented on index.html
> +      </div>
- [ ] I would suggest you please increase the font weight of the heading. Also if you see the content after that heading then you will find the border with min-width please implement accordingly.
### Your design
![hiz](https://user-images.githubusercontent.com/81727988/217806996-ddd3eb7a-9268-4f92-aab8-93a883e57cd2.png)

### Original design
![original](https://user-images.githubusercontent.com/81727988/217807018-93507564-52bb-4314-97ef-7288e0dca154.png)

2023-02-09 13:06 UTC, roshan-bajgain commented on index.html
> +
- [ ] You should stick to the design as much as possible. please use the border on every card and make the size adjustable as there is a gap between the left and right and `Historic places in Oromia to Visit` is inside the black background. See the image below for reference.
- [ ] Also make sure you have black stripes background. See image below for reference
### Your design
![his](https://user-images.githubusercontent.com/81727988/217808994-c16469d9-6559-4f24-b3a5-c34b05d8daff.png)

### Original design
![fimga](https://user-images.githubusercontent.com/81727988/217809026-7331aeb1-9dbf-4b94-b3c5-ea2e86b75536.png)

2023-02-09 13:06 UTC, roshan-bajgain commented on index.html
> +    <div class="footer" id="">
- [ ] Please adjust the spacing to match the original design. The first speaker and the second should be on the same line. The image covers the equal height with the content on the right of the image. Please try to adjust the spacing. See the image below for reference. Also please decrease the number of height and make is smaller to match the design
### Your design
![his](https://user-images.githubusercontent.com/81727988/217810508-8f79a3b5-8f68-43be-99c8-1fcca60627a1.png)

### Figma design

![original](https://user-images.githubusercontent.com/81727988/217810547-c9f7ce55-1c40-4a1d-a193-7a8822fb0adf.png)

2023-02-09 13:06 UTC, roshan-bajgain commented on about.html
> +          </p>
- [ ] In this about section, the page title at the middle of the page, and the content should have a border with different background. This `VisitOromia@2023` should be central to the page please implement it.
- [ ] If you see the design then you will find a white background. See implement it. Please remove the `"Hello, Tourist!"` in the about section.
### Your design
![his](https://user-images.githubusercontent.com/81727988/217812294-22ede930-d120-4d64-b358-549a685f60bc.png)

### Original design
![orignal](https://user-images.githubusercontent.com/81727988/217812313-336477bd-27b4-41bb-b6ae-799adb8f804c.png)

2023-02-09 13:06 UTC, roshan-bajgain commented on about.html
> +        </h2>
- [ ] If you see the design then the title is in the middle and the content should have limited width please do so. There is gap on left and right
- [ ] There is a `hx` tag after the logo and the logo has border on it please see the design and implement it. Please use the same color and font for content
### Your design
![his](https://user-images.githubusercontent.com/81727988/217814386-a135a134-9c19-4919-8028-428404a8719a.png)

### Original design
![original](https://user-images.githubusercontent.com/81727988/217814428-db9d2d7a-f7b9-43f7-bf1f-e17b2852d18e.png)

2023-02-09 13:06 UTC, roshan-bajgain commented on about.html
> +    </div>
- [ ] As per the requirement the image should have gaps on right and left of the page and the footer has a black background and content on the right side of the footer. Please implement it. See the image below for reference
### Your design
![his](https://user-images.githubusercontent.com/81727988/217815277-5977d1d8-c001-47f0-a77c-89a8a7b7231b.png)


### Figma design

![original](https://user-images.githubusercontent.com/81727988/217815315-a99a29a6-cf4c-49d5-9414-5484e2a2d4e0.png)

2023-02-09 13:06 UTC, roshan-bajgain commented on script.js
> +});
- [ ] When the hamburger buttons are open in the mobile version then I cannot go to the about section by clicking on `about section please fix it. There should be both menus for `Home Page` and `About Page` for navigation. Please do so as well.

2023-02-09 13:06 UTC, roshan-bajgain commented on index.html
> +        <hr class="hr" />
- [ ] There should not be more than 1 `h1` tag per page please remove the other `h1` tag here for semantic reason

2023-02-09 13:06 UTC, roshan-bajgain commented on index.html
> +        <h1 class="about-heading">Featured Speakers</h1>
- [ ] There should not be more than 1 `h1` tag per page please remove the other `h1` tag here for semantic reason

2023-02-09 13:06 UTC, roshan-bajgain commented on index.html
> +      </div>
- [ ] Please wrap this section with `nav` tag for better semantic HTML.

2023-02-09 13:06 UTC, roshan-bajgain commented on index.html
> +
- [ ] It's better to use section tag here for better semantic HTML.

2023-02-09 13:06 UTC, roshan-bajgain commented on index.html
> +    </div>
- [ ] It's better to use a footer tag in the footer for better semantic HTML.

2023-02-09 13:06 UTC, roshan-bajgain commented on about.html
> +    </div>
- [ ] Please use section tag for better semantic HTML.

2023-02-09 13:06 UTC, roshan-bajgain commented on about.html
> +    </div>
- [ ] I would suggest you please use the footer tag for the footer it indicates better semantic HTML.

2023-02-09 16:07 UTC, osamaashraf6 requested changes
Hi @amanuelbelete95 😊, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)


## Highlights💯🎈🪄✔️

- [x] Descriptive READme file in a professional way.✔️
- [x] No linter errors. ✔️
- [x] Good usage in correcting GitHub flow.✔️
- [x] Nice design.✔️


## Suggested changes
- You did well by recording the loom video, but as I see you didn't show us The video contains a demo of the project, showing the pages in different screen sizes, so kindly try to make that 😊for the requirements 

- Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-02-09 16:07 UTC, osamaashraf6 commented on index.html
> +                <li class="red-border"><a href="">CC Campaign</a></li>
- [ ] As stated by the previous reviewer kindly try to stick to the color of the text here to be nice like the Behance 😊
- [ ] Also please give the cc campaign the correct color like the Behance 💯

> Check below to see the difference 😊⤵️

| Figma design | Your design| 
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/83360636/217855182-fbedecbb-d44c-453e-9117-b214da41807e.png)    |    ![image](https://user-images.githubusercontent.com/83360636/217854977-5b5c9a8d-80c4-4ecc-b39c-cfdcdf5c1baf.png)   |

2023-02-09 16:07 UTC, osamaashraf6 commented on index.html
> +          </p>
- [ ] You did a great job at adding the border at the content, but as stated by the previous reviewer kindly try to give min width to the content to be like the Behance

> Check below to see the difference 😊⤵️

| Figma design | Your design| 
| --- | --- |
|   ![image](https://user-images.githubusercontent.com/83360636/217856588-2b7191ef-7230-4d72-af94-9272f16e9bfd.png)   |     ![image](https://user-images.githubusercontent.com/83360636/217856532-8801ebd8-3fa8-445f-aafa-7f282d211986.png)  |

2023-02-09 16:07 UTC, osamaashraf6 commented on index.html
> +        </p>
- [ ] You did well at adding the border, but  As stated by the previous reviewer  kindly  try to make the size adjustable as there is a gap between the left and right and Historic places in Oromia to Visit are inside the black background. See the image below for reference.
- [ ] Also try to give the section the same background image like the Behance to be nice 

> Check below to see the difference 😊⤵️

| Figma design | Your design| 
| --- | --- |
|    ![image](https://user-images.githubusercontent.com/83360636/217857722-c98d3cab-0011-4ed0-a02f-891f15e5f4a2.png)  |    ![image](https://user-images.githubusercontent.com/83360636/217857634-0433df65-7add-4051-a89e-6e6c1dd726e4.png)   |

2023-02-09 16:07 UTC, osamaashraf6 commented on script.js
> +
- [ ] As stated by the previous reviewer here Please adjust the spacing to match the original design. The first speaker and the second should be on the same line. The image covers the equal height with the content on the right of the image. Please try to adjust the spacing. See the image below for reference. Also please decrease the height and make is smaller to match the design💯

> Check below to see the difference 😊⤵️

| Figma design | Your design| 
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/83360636/217858588-67617072-09d8-456c-9730-b7f4d301d5fc.png)    |   ![image](https://user-images.githubusercontent.com/83360636/217858520-e39264e6-c89d-4371-b4eb-2f11836af98c.png)    |

2023-02-09 16:07 UTC, osamaashraf6 commented on about.html
> +          astounded.
- [ ] As stated by the previous reviewer kindly try In this about section, to make the page title at the middle of the page  This VisitOromia@2023 should be central to the page please implement it.
- [ ] Also If you see the design then you will find a white background. See implement it. Please remove the "Hello, Tourist!" in the about section.

> Check below to see the difference 😊⤵️

| Figma design | Your design| 
| --- | --- |
|    ![image](https://user-images.githubusercontent.com/83360636/217859805-8a98bdc7-512b-42cc-b989-458f8d806153.png)  |   ![image](https://user-images.githubusercontent.com/83360636/217859711-94e6e895-059d-40a0-85a0-7dbb97e6ef16.png)   |

2023-02-09 16:07 UTC, osamaashraf6 commented on about.html
> +          developer  who were qualified by visit-oromia tourism commission. <br> After
- [ ] Kindly as stated by the previous reviewer If you see the design then the title is in the middle and the content should have limited width please do so. There is a gap between left and right

> Check below to see the difference 😊⤵️

| Figma design | Your design| 
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/83360636/217860865-c2659931-146b-4f36-ae9e-2d756cba0a82.png)    |     ![image](https://user-images.githubusercontent.com/83360636/217861113-47ba58ea-957b-4224-afae-41c790f8e38f.png)  |

2023-02-09 16:07 UTC, osamaashraf6 commented on about.html
> +      </div>
- [ ] As stated by the previous reviewer As per the requirement the image should have gaps on right and left of the page and the footer has a black background and content on the right side of the footer. Please implement it. See the image below for reference

> Check below to see the difference 😊⤵️

| Figma design | Your design| 
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/83360636/217861947-5581fa8f-c69c-4ece-b230-29d9bbff28db.png)    |    ![image](https://user-images.githubusercontent.com/83360636/217861848-15798ffb-1122-4be5-be5d-7fbd6afe57e1.png)  |

2023-02-09 16:07 UTC, osamaashraf6 commented on script.js
> +});
- [ ] As stated here by the previous reviewer  When the hamburger buttons are open in the mobile version then I cannot go to the about section by clicking on the about section please fix it. There should be both menus for Home Page and About Page for navigation. Please do so as well.
- [ ] Also [Optional]  kindly consider fixing the responsiveness at the mobile version as you see there are some issues in the responsiveness😊

> Check below to see the difference 😊⤵️

| Your design| 
| --- | 
|   ![Recording 2023-02-09 at 17 45 56](https://user-images.githubusercontent.com/83360636/217863309-66782031-40f6-404f-9d4b-b7645c141f08.gif)  |

2023-02-09 16:07 UTC, osamaashraf6 commented on index.html
> +        <hr class="hr" />
- [ ] As stated here by the previous reviewer please, There should not be more than 1 h1 tag per page please remove the other h1 tag here for a semantic reasons😊

2023-02-09 16:07 UTC, osamaashraf6 commented on about.html
> +        </h1>
- [ ]  As stated here by the previous reviewer please, There should not be more than 1 h1 tag per page please remove the other h1 tag here for a semantic reasons😊

2023-02-09 16:07 UTC, osamaashraf6 commented on about.html
> +        <hr class="part" />
- [ ] As stated by the previous reviewer I would suggest you please use the footer tag for the footer it indicates better semantic HTML.😊

2023-02-09 16:07 UTC, osamaashraf6 commented on README.md
>  <p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] You did well at writing about the original design,but I see that the link for the design is broken,so please try to use the correct link as stated by the previous reviewer 😊

2023-02-09 19:43 UTC, Kamba56 requested changes
Hi @amanuelbelete95, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-02-09 19:43 UTC, Kamba56 commented on about.html
> +    <section class="home-page">
- [ ] As stated by the previous reviewers, kindly centralize the contents of this section to match the given template.
### Your design
![image](https://user-images.githubusercontent.com/94551484/217915995-b6cb0a10-c0f6-4818-8850-4669871375c7.png)
### Design template
![f1](https://user-images.githubusercontent.com/94551484/217916281-c7ea492d-40c3-4728-ad50-c458ce908b10.png)

2023-02-09 19:43 UTC, Kamba56 commented on about.html
> +      <div class="live-cont">
- [ ] As requested by previous reviewers, kindly add spaces to the left and right of this container in the desktop view. Consider adding a padding left and right of 200px to the destop view to match the design template.
### Your design
![image](https://user-images.githubusercontent.com/94551484/217919448-5a833708-4111-4552-8c0c-2ec12962e50b.png)

### Design template
![f2](https://user-images.githubusercontent.com/94551484/217919576-a21852ad-3267-447f-bb6c-c3e62d6c018d.png)

2023-02-09 20:35 UTC, vickymarz approved these changes
Hi @amanuelbelete95, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-09 20:41 UTC, merged